export const SHOP_ACTIONS_TYPES = {
    GET_SHOP_DATA: "GET_SHOP_DATA",
    FETCH_DATA_START:'FETCH_DATA_START',
    FETCH_DATA_SUCCESS:'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILED:'FETCH_DATA_FAILED',
    SET_CURRENT_CARD:"SET_CURRENT_CARD",
    SET_CARD_INBUCKET:"SET_CARD_INBUCKET",
    SET_FAVLIST:"SET_FAVLIST",
    REMOVE_CARD_FROMBUCKET:"FROMBUCKET",
    ORDER_SUBMIT:"ORDER_SUBMIT"
}