export const SHOP_ACTIONS_TYPES = {
    GET_SHOP_DATA: "GET_SHOP_DATA",
    SET_CURRENT_CARD:"SET_CURRENT_CARD",
    SET_CARD_INBUCKET:"SET_CARD_INBUCKET",
    SET_FAVLIST:"SET_FAVLIST",
    REMOVE_CARD_FROMBUCKET:"FROMBUCKET"
}